### ISSUE TITLE
how to using it ,plz?

### ISSUE THREAD

**Issue by yorkbai** [akohlbecker/aw-watcher-tmux#1]
I think it can help me and installed this plugin in tmux , how to using it ?

**Comment by akohlbecker** [comment]
First of all you need to install ActivityWatch. This point was missing in the README. I added some more details to the **Installation** chapter and added a **Usage** chapter. 
I hope that the README is now complete and comprehensible.

Does this help you to with using the plugin?

**Comment by akohlbecker** [comment]
I guess this issue is being solved as there was no further comment to this issue.
